# Generated by Django 3.2.8 on 2021-10-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickName',
            field=models.TextField(default='', max_length=15),
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
